### ISSUE TITLE
WIP writeup for security section in readme

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#100]
## using a deployed bridge

ensure the contracts deployed match the contracts in the repo. TODO how

**ensure you trust a majority of authorities to be honest**

a majority of authorities can move the ether you've deposited.
if they are honest they only will do so when you've initialized a withdraw.
if they are malicious they can do it freely.

you should only use the bridge if you trust n of the validators to be honest

## trust

`HomeBridge` trusts `requiredSignatures`signatures from `authorities`

`ForeignBridge` trusts `requiredSignatures`signatures from `authorities`

## what are possible attacks on the bridge?

if `requiredSignatures` authorities collude they can make up deposits and withdrawals. but then the security of the entire PoA chain is compromised anyway. through the bridge one could use mainnet ether in this case. **need to trust majority of authorities running PoA**

## consider the following scenario (to understand the security model)

a malicious actor charlie sets up a PoA chain with authorities and a bridge to connect it to mainnet.

the deployed contracts are exactly the audited contracts, tested, trusted ones from the bridge repo. 

people start depositing ether into HomeBridge to use the ForeignBridge tokens.

it turns out that charlie had control over all the authorities.

suddenly charlie switches all bridge processes/authorities to signing off on fake (no Withdraw event on foreign) withdrawals to addresses that charlie has the private key to.

HomeBridge trusts a majority of authorities and accepts the withdrawals.

charlie now has all the ether the users deposited into HomeBridge.

of course every PoA chain fails if a malicious actor controls a majority of authorities.
the bridge just makes it possible to loose mainnet ether this way.
**ask yourself for every bridge deployment: do i trust a majority of authorities?**

---

the security of the bridge should always hold unless an authority majority is malicious

---

if there is no honest majority then security is not compromised (unless a majority is colluding) but liveness is compromised.

relays won't happen and the bridge won't function. once there is again a majority that is honest and not faulty the bridge can continue without any safety issue

---

encourage others to try to break it

**Comment by tomusdrw** [comment]
That's going to change anyway, closing.
