### ISSUE TITLE
improve checks for underflows/overflows

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#102]
currently checks for underflows/overflows and operations subject to them are separate and often several lines apart.

this is brittle. it's too easy to accidentally change one without adapting the other introducing bugs.

add a SafeMath library ala https://theethereum.wiki/w/index.php/ERC20_Token_Standard that auto reverts on underflows/overflows

**Comment by debris** [comment]
interesting, I didn't know about this library! 👍
