### ISSUE TITLE
ForeignBridge is ERC777

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#103]
https://github.com/ethereum/EIPs/issues/777

ERC20 is a standard with massive adoption. ERC777 has several improvements over ERC20 but is still just a proposal without adoption.

**Comment by rstormsf** [comment]
Actually, it's backwards compatible ERC20 token with some improvements.

**Comment by snd** [comment]
i don't think so.

look at the `Specification` section: https://github.com/ethereum/EIPs/issues/777

it doesn't have the `transfer`, `transferFrom` and `allowance` functions (and several others) of ERC20 (https://theethereum.wiki/w/index.php/ERC20_Token_Standard).

one can make a contract that is both ERC777 and ERC20 and call it a backwards compatible ERC777.
ERC777 isn't ERC20 by default though!

**Comment by snd** [comment]
this could be build on top of the arbitrary message passing bridge in a separate repository. doesn't belong here
