### ISSUE TITLE
vote on change in validator set

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#107]
enable authorities to vote on a new fixed validator set.

intermediary step between "validator set immutable after contract creation" (current) and "contract based ValidatorSet" (#33).

have to be careful to avoid race conditions with deposits and withdraws that are in progress

*as discussed with @bjornwgnr in person on 2018-01-30*

**Comment by tomusdrw** [comment]
We should rather impl #33 right at the start.
