### ISSUE TITLE
withdraws can be burned by relayers through setting very high gas price

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#112]
*thanks to @bjornwgnr for finding this*

# problem

given a `ForeignBridge.CollectedSignatures` event that has not yet
been relayed i.e. doesn't have a matching `HomeBridge.Withdraw`.

anyone can call `HomeBridge.withdraw` to relay the withdraw.
this is by design. `HomeBridge.withdraw` only trusts the list of authorities.
signatures of those authorities (on the message) are passed to `withdraw`.

as with any transaction the sender of `withdraw` can freely choose the gas price.
currently (introduced by #77) `estimatedGasCostOfWithdraw * tx.gasPrice`
is subtracted from the withdrawn value and transfered to `sender` to pay
for the relay.

since the transaction sender can freely choose the gas price they can burn a users withdraw by setting an extremely high gas price.

# solution

add additional param `homeGasPrice` to
`ForeignBridge.transferHomeViaRelay` so the interface looks like
`ForeignBridge.transferHomeViaRelay(recipient, value, homeGasPrice)`.

end user can easily find out a gas price on something like https://ethgasstation.info/.

add `homeGasPrice` to message that is signed and relayed.

then in `HomeBridge.withdraw(vs, rs, ss, message)`
require `require(tx.gasPrice == homeGasPrice)` forcing the sender of
the withdraw to use the user specified gas price.

this solution has other nice properties:

we now know the `homeGasPrice` on foreign since it's provided by the enduser.
so we can require `require(estimatedGasCostOfWithdraw * homeGasPrice > value)`
in `Foreign.transferHomeViaRelay` and revert such withdraws that
don't have enough value to pay for the relay.
this improves UX since such withdraws are currently ignored by bridge processes
which, while being well documented and sensible, can lead to confusion.

the `homeGasPrice` is documented in the `ForeignBridge.Withdraw` event
so it's transparent if the relay transaction doesn't get mined on `home`
because of too low a gas price.

end users now have control over the cost/latency tradeoff of their relay through
the `homeGasPrice`.

## edge case

provided gas price is too low and transaction doesn't get mined.

in `HomeBridge.withdraw` we could allow only `recipient` to change the gas price
by changing the require to `require(recipient == msg.sender || tx.gasPrice == homeGasPrice)`.
now the recipient can manually rescue by providing a new gas price and paying it
themselves.

**Comment by Ri2k18** [comment]
Hi I have Eth address for parity signer, how  can I use my eth there if I forgot my recovery phrase
Plese help me. Thanks

**Comment by snd** [comment]
hey @Ri2k18, please ask your question again in the right repo https://github.com/paritytech/parity-signer
