### ISSUE TITLE
Logging bridge

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity-bridge#116]
It would be nice to have some sort of logs for the bridge output:
Is it working?
has it received a tx?
has it confirmed/signed a tx?
has it transferred the deposit?
has it withdrawn the deposit?

There are no logs right now, kind of black box solution

**Comment by snd** [comment]
related https://github.com/paritytech/parity-bridge/issues/97

would like to build it as a separate tool to keep the relay processes simple

**Comment by akolotov** [comment]
Actually logs could be enabled by setting environment variable `RUST_LOG` in `info` value.
For example,
`env RUST_LOG=info ./bridge --config config.toml --database db.toml`

But currently the issues with tracing `deposit_relay` thread exists: https://github.com/paritytech/parity-bridge/issues/118

**Comment by snd** [comment]
yes, there is logging using the `log` crate macros. as mentioned by @akolotov console output for logs can be enabled as usual with the `RUST_LOG` env var.

i think we can close this issue. let me know

**Comment by snd** [comment]
closing this because there is logging and it can be enabled through `env RUST_LOG=info ...`. please open another issue if specific logging is missing/required : )
