### ISSUE TITLE
possibly get rid of withdraw message

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#117]
just a thought. would love some feedback:

currently on withdraw the bridge assembles a `message` by concatenating the data required to execute withdraw.
authorities then sign that message. assembling the message and extracting fields makes up a chunk of code.

could we not simply pass in the separate parts of the withdraw data as arguments where needed, hash them and let authorities sign the hash? (the message gets hashed anyway before signing).

instead of the message we could simply use the hash of the message in many places.

on a similar note: why not pass around the signature fields v,r,s as separate args instead of converting to/from signature `bytes`?

instead of https://github.com/paritytech/parity-bridge/blob/ddc54802dd73a4f210c0ba20b7c6206c18d70615/contracts/bridge.sol#L446 we'd have:

```sol
function submitSignature(uint8 v, bytes32 r, bytes32 s, address recipient, uint value, bytes32 transactionhash) public onlyAuthority() {
    let message = keccak256("\x19Ethereum Signed Message:\n", "32", keccak256(recipient, value, transactionHash);
    require(ecrecover(message, v, r, s) == msg.sender);
    // ...
}
```

instead of https://github.com/paritytech/parity-bridge/blob/ddc54802dd73a4f210c0ba20b7c6206c18d70615/contracts/bridge.sol#L228 we'd have:

```sol
function withdraw(uint8[] v, bytes32[] r, bytes32[] s, address recipient, uint value, bytes32 transactionHash) public allAuthorities(v, r, s, recipient, value, transactionHash)
    // ...
}
```

this might increase gas costs a tiny bit. on the plus side it makes things more straightforward (less and simpler code, no assembly required), self explaining (currently we have a big comment explaining the message structure) and less error prone.

**Comment by debris** [comment]
> on a similar note: why not pass around the signature fields v,r,s as separate args instead of converting to/from signature `bytes`?

There were two reasons why I decided to pass these args together.

1. It's cheaper :) but if there is not a big gas usage difference, I'm happy with the changes
2. `submitSignature` could be potentially reused to sign different types of messages.  But if it's not a case, I'm also happy with the changes
