### ISSUE TITLE
introduce deposit limits for test deployment

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#119]
@bjornwgnr and me just discussed this in person. @bjornwgnr raised the issue.

we want to do a test deployment between mainnet and kovan.

if there are bugs in the bridge ether deposited into `HomeBridge` could be frozen forever.

we'll publicize the test deployment with a big disclaimer:

> this is an alpha test deployment. expect bugs. only deposit small amounts of ether that you're prepared to loose

furthermore we want to limit the extent of loss for any accidental misuse:

- reject deposits that would cause the bridge to hold more than 10 ether
- reject deposits of more than 1 ether

this is a very easy change:

in `HomeBridge.deposit` https://github.com/paritytech/parity-bridge/blob/68c99498049b0568c0ac08f0acdeac5fd2b13bd5/contracts/bridge.sol#L204 add

```sol
require(msg.value <= 1000000000000000000);
require(this.balance + msg.value <= 10000000000000000000);
```

i don't think we should commit this to master.
should we maintain a separate branch for this?
should we make them config options? i don't think it's worth it.
other ideas?

**Comment by snd** [comment]
@debris what are your thoughts on this?

**Comment by debris** [comment]
let's merge into master, but with configurable limits. I think this might be useful in future.

e.g.

every authority automatically processes transactions with value higher than X
it requires 'manual' acceptance of an authority to process a transaction with value above this limit

**Comment by snd** [comment]
cool

while we're at it we could also introduce a max withdraw so

**Comment by bjornwgnr** [comment]
Afaict, https://github.com/paritytech/parity-bridge/pull/121 introduces limits only for 'max_total_home_contract_balance' & 'max_single_deposit_value' rather than also for withdrawals.

>every authority automatically processes transactions with value lower than X
it requires 'manual' acceptance of an authority to process a transaction with value above this limit

^ sounds like @debris is looking for an option to limit withdrawals as well. Could you confirm?

**Comment by snd** [comment]
`max_total_home_contract_balance` and `max_single_deposit_value` are very useful as they reliably (easy to audit, 1 function, 2 lines) limit the total amount of mainnet ether that can be lost if the bridge is faulty or compromised in any way!

i'm less convinced that limiting withdraws is a good idea at this point.
it would require checks on both sides and add more complexity.
on its own it would only make it slightly more cumbersome (require multiple transactions) for an attacker that has compromised the authorities to withdraw all ether.

**Comment by snd** [comment]
later on and in addition with other security features limiting withdraws might be useful.

i wrote this in the bridge riot channel on feb 6:

> how do we react when a majority of validators is compromised? i know the PoA network is unusable then / after then. in the context of the bridge this is an issue because real mainnet ether or tokens are at stake and a majority of validators has free reign over them (no way around that). dapp owners considering running their dapp on kovan and using the bridge worry about that. my opinion: this is an unrecoverable scenario and one the security of the bridge doesn't/can't/shouldn't cover. we could add limits to how much can be transferred out of the bridge on main (per transaction, within certain block range) so an attack like this can only proceed slowly (otherwise they could steal everything in one transaction). during testing we could add a special set of recovery addresses [controlled by the authorities] any one of which can stop the bridge (to shut down the attack) and afterwards a majority vote [of recovery addresses] can move funds freely so nothing is lost

**Comment by snd** [comment]
resolved in https://github.com/paritytech/parity-bridge/pull/121
