### ISSUE TITLE
consider moving deployment code out of bridge processes into separate script

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#120]
deployment needs to be done once per bridge.

it would simplify things if we had a separate deploy script/process that focuses exclusively on deployment and generating the initial database file.

that file would then be distributed to all authorities running the bridge.

both the deploy process and the run process would become more simple

**Comment by snd** [comment]
would also make sense to have separate configs.
most config options are either only required for deploying or only required for running the bridge.
currently requires both parties to set all config options.

when running the bridge could query `estimated_gas_cost_of_withdraw` and other similar options from the contracts themselves so we remove issues arising from having conflicting values in config and contract.

**Comment by snd** [comment]
validators that just run the bridge wouldn't have to bother with anything concerning deployment

**Comment by snd** [comment]
deployer does not even need to be authority

compiling `deploy` should compile everything that's required to deploy
into the binary

possibly have two database files. one for each of the sides.

possibly rename `database` to `state`

possibly not put contract addresses into state as they don't change

possibly split deploying home and deploying foreign.
deploying both is simply running one after the other.

validator processes should only be coupled to deployed contracts through contract addresses and authority their address being in the validator sets

**Comment by debris** [comment]
> deployer does not even need to be authority

👍 

> compiling deploy should compile everything that's required to deploy
into the binary

👍 

> possibly have two database files. one for each of the sides.

~I don't know if this is a good idea.~ It may simplify making a bridge generic 👍 

> possibly rename database to state

👍 

> possibly not put contract addresses into state as they don't change

I see what you are doing here :) After deployment, authority is given only a single address that needs to be passed as a command line param for a bridge 👍 

> possibly split deploying home and deploying foreign.
> deploying both is simply running one after the other.

like that? 

```
$ ./deploy --home
0x170e5030942c9e2afc8445ac65b00b98f5b29472
./deploy --foreign
0x803c7acc17a7651eea284b02ade8aa2bbbf36c70
```

👍 

> validator processes should only be coupled to deployed contracts through contract addresses and authority their address being in the validator sets

I'm not sure I understand this one :)

**Comment by snd** [comment]
> I see what you are doing here :) After deployment, authority is given only a single address that needs to be passed as a command line param for a bridge

trying to do this : ) not a single address but the pair of addresses of both contracts (main and side). if it works out it would simplify things quite a bit

> like that?

yes, either exactly like that or similar

> I'm not sure I understand this one :)

that's not even a real sentence i wrote there ; )

i meant that bridge nodes (the processes) should ideally only be coupled to the deployed contracts through the bridge nodes knowing the addresses of both contracts and the contracts having the addresses used by the bridge nodes in the validator set.

**Comment by snd** [comment]
resolved in https://github.com/paritytech/parity-bridge/pull/134
