### ISSUE TITLE
Can't withdraw from Home. Message is 234 length while it should be 116

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity-bridge#124]
1. Here is a signature:
https://kovan.etherscan.io/tx/0x2abf20e0c8d3e46833fe70487e74a6726711b4d53cd89499e8e3996d70d87ad0

It emited CollectedSignature event:
msgHash:
0x97c18355ba680d4f458c00b39906dee3ab77e366b2fa29fc027416b380ead8ed

Now if I want to get the message, I'd call `message(msgHash)` on ForeignBridge:
which returns the following:
```
0x0039f22efb07a647557c7c5d17854cfd6d489ef300805f2bd9fbb40100000000000000000000000000000000000000000000000000d6093bc86912a0e3810f9c054915e7f07870a35949bfc3f2e194653ba462b100ca9a3b00000000000000000000000000000000000000000000000000000000
```
which is 234 long length message.
So, something is not being stored correctly in order to get actual message to submit withdraw request from Home

Deployed POA-Home:
```
Home-POA: https://poaexplorer.com/address/search/0x8001194b6a8a386a0dc83d63e54842b0cd37e8de
Home-abi: https://github.com/poanetwork/bridge-ui/blob/master/src/homeAbi.json

Foreign-Kovan1: https://kovan.etherscan.io/address/0x7c4d0472335a560a3e855e8b570796b43ab4e27a
MsgHash: 0x97c18355ba680d4f458c00b39906dee3ab77e366b2fa29fc027416b380ead8ed

Foreign-Kovan2:
https://kovan.etherscan.io/address/0x4cfadf1d34f9f85a6b47a6a1b403c52cc6038a70#readContract
MsgHash: 0x1dacece52c94147096154267dcc711c0f468dfaf594d2231e72baecbe3a832a3
r:"0xf3b37f215c0b4bacc5460acf1e928279532154b84f37628f1100ab0bbee7c93e"
s:"0x053be9793b561b9070285aaa3d6e7fdfc5fe6f8048491d205935459fe31ba4ad"
v:27
```
any help ? why I can no longed call `withdraw` on Home? it feels like I'm being stuck on `require(message.length == 116)`

**Comment by snd** [comment]
> I'd call message(msgHash) on ForeignBridge

how are you calling it?

a message is 116 bytes long.

```
0x0039f22efb07a647557c7c5d17854cfd6d489ef300805f2bd9fbb40100000000000000000000000000000000000000000000000000d6093bc86912a0e3810f9c054915e7f07870a35949bfc3f2e194653ba462b100ca9a3b00000000000000000000000000000000000000000000000000000000
```

is the hex representation of a message. a hex representation is 2x the bytes.
removing the "0x" prefix that just signifies hex leaves us with 232 bytes.
232 / 2 = 116 bytes.

remove the "0x" prefix. then convert from hex to bytes.

hope this helps

**Comment by snd** [comment]
closing this for now. reopen as needed
