### ISSUE TITLE
Little-endian encoding does not match with contract integers

### ISSUE THREAD

**Issue by akolotov** [paritytech/parity-bridge#127]
Before the commit https://github.com/paritytech/parity-bridge/commit/500004393033fe03c995363e086c5679a6caebf5 `withdraw_confirm` constructed the message from the numbers as they were got from `Withdraw()` event:

https://github.com/paritytech/parity-bridge/blob/41543ca40e510070f77f975c1a69d4b253fd38fa/bridge/src/bridge/withdraw_confirm.rs#L29-L32

But later this behavior was changed to encode integers to little endian format:

https://github.com/paritytech/parity-bridge/blob/500004393033fe03c995363e086c5679a6caebf5/bridge/src/bridge/withdraw_confirm.rs#L80-L86

where `to_bytes` is 

https://github.com/paritytech/parity-bridge/blob/500004393033fe03c995363e086c5679a6caebf5/bridge/src/message_to_mainnet.rs#L46-L55

It led to the issue that integers which are coming to _HomeForeign_ as part of the message of `withdraw()` are in the little endian format also. That's why, for example, instead of having 1 gwei of  `gasPrice` you will have the integer which is `00ca9a3b0000000000000000000000000000000000000000000000000000000000000000` in hex.
Therefore the transaction cannot be completed successfully.

**Comment by akolotov** [comment]
Another intersting fact is that

https://github.com/paritytech/parity-bridge/blob/054aa6a86873ce22d1215130d6d516ee9f1a3980/integration-tests/tests/basic_deposit_then_withdraw.rs#L258-L264

does not catch the issue since the balance of `user_address` is definitely above zero as per this description:

https://github.com/paritytech/parity-bridge/blob/054aa6a86873ce22d1215130d6d516ee9f1a3980/integration-tests/tests/basic_deposit_then_withdraw.rs#L96-L99

**Comment by akolotov** [comment]
Here is a proposed fix for the issue: https://github.com/poanetwork/parity-bridge/commit/57bce4579a445670e11f53615336637407a821d5

**Comment by snd** [comment]
thanks for catching this. i'll include the fix soon and adapt the test to ensure we never regress on this!

**Comment by snd** [comment]
shows that we need more integration tests. this should have been caught
