### ISSUE TITLE
add integration test with multiple authorities

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#133]

**Comment by debris** [comment]
Authorities does not have to be online at the same time, so the simplest integration test could be done by: 

- starting parity as authority A, 
- relaying transactions
- closing parity
- starting parity as authority B,
- relaying transactions
- verifying that everything has been relayed properly

**Comment by tomusdrw** [comment]
A basic test is in the repo already, we might consider a new one for the poa<>substrate bridge in the future.
