### ISSUE TITLE
bridge node should fetch required_signatures from contract not from config

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#140]
bridge node crashes if contract has `required_signatures` = 1 and config has `required_signatures` > 1. **information should only be in one place.** fetching from contract removes possibility of mismatch.

fetching from contract allows all bridge nodes to use same settings without updating config file everywhere.

same could be done for:

- required_confirmations
- gas limits

having required_confirmations in the contract could even allow us to prevent authorities from submitting their signature on a withdraw that has not yet been confirmed enough times.

related #141

**Comment by debris** [comment]
so `required_signatures` should be set only once during deployment :)

**Comment by tomusdrw** [comment]
Merging as meta issue at #33
