### ISSUE TITLE
[BUG] Bridge dies with 'eth_sendTransaction timed out' message during stress testing

### ISSUE THREAD

**Issue by akolotov** [paritytech/parity-bridge#149]
Network setup:
* Home: a PoA testnet (Sokol)
* Foreign: Ropsten
* Bridge is built from `master` of paritytech/parity-bridge

There are 1200 deposit transactions sent successfully to `HomeBridge` contract by a special python script. It took 11 blocks to validate all transactions.
https://sokol-explorer.poa.network/block/1428549
https://sokol-explorer.poa.network/block/1428550
. . .
https://sokol-explorer.poa.network/block/1428558
https://sokol-explorer.poa.network/block/1428559

The bridge discovered part of these transactions, tried to relay them (just 40 were handled), but crashed by some reason:
```
INFO:bridge::bridge::deposit_relay: got 60 new deposits to relay
INFO:bridge::bridge::deposit_relay: relaying 60 deposits
Request eth_sendTransaction timed out
```
The database file is not updated so the restart of the bridge caused the same error. There is no way to start bridge without manual modification of database but it causes lock of funds on `HomeBridge` contract side since incomplete amount of tokens is transfered by `ForeignBridge` contract.

Here is details:
* `ForeignBridge` contract: https://ropsten.etherscan.io/address/0xf3ee321df87781864f46f6464e764c2827fca73b (40 txs are validated in 2842436, 2842451, 2842454 and 2842455).
* configuration files and log messages produced by the bridge: https://gist.github.com/akolotov/13a014bc698e483dd36773bbf462a76f

**Comment by akolotov** [comment]
I  did not check but my expectation that similar issue will occur if Ropsten will be as Home, PoA will be as Foreign and the bridge will be trying to relay mass of withdraw txs.

**Comment by snd** [comment]
i'll look into this. will try to do #150 to reproduce it

**Comment by debris** [comment]
It's possible to specify `request_timeout` in [config file](https://github.com/paritytech/parity-bridge#main-options) now. if you increase this number to more than 5 seconds, everything will work as expected.

There is not much more we can do, as this exception is not caused by the slow bridge, but unresponsive node which choked because of number of requests it has to process
