### ISSUE TITLE
IPC -> RPC

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#153]
users keep asking for this.

makes the bridge easier to configure and **work with parity/geth nodes on other machines** which is needed in common deployment setups.

we could allow users to choose IPC or RPC. i'm slightly against that. adds complexity. imho we don't need the performance of IPC for the bridge. i know IPC is faster. doubt this will be a bottleneck anytime soon. transaction throughput on the two chains is the bottleneck.

**Comment by debris** [comment]
it should be fairly easy to implement as most of the codebase is generic over transport type :)
