### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#156]
- finish refactoring of rust code in preparation for arbitrary message passing and to leave repository in a clean state
  - https://github.com/paritytech/parity-bridge/pull/159
  - incluces IPC -> RPC (https://github.com/paritytech/parity-bridge/issues/153)
- arbitrary message passing (https://github.com/paritytech/parity-bridge/pull/126)

**Comment by debris** [comment]
replaced by #202
