### ISSUE TITLE
switch from error-chain to https://github.com/rust-lang-nursery/failure

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#163]
i've used https://github.com/rust-lang-nursery/failure in other projects and found it much nicer to work with than error_chain

> It is intended to replace error management based on std::error::Error with a new system based on lessons learned over the past several years, including those learned from experience with quick-error and error-chain.

curious to hear others opinions on it

**Comment by debris** [comment]
is it interoperable with `error-chain` errors?

**Comment by snd** [comment]
i thought it was. though i was running into some issues yesterday with `web3::Error` which uses error chain. `failure` requires things implementing `Fail` to be `Sync` and `Send` which is annoying. i'll probably hold off on this for now

**Comment by snd** [comment]
closing this for now. might reopen at a later date
