### ISSUE TITLE
Using solcjs instead of solc

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/parity-bridge#169]
`solc` and `solcjs` both can be used to compile smart contracts. One drawback of using solc is that solc is not easily available on many platforms. Specifically, I am talking about `centos`.

Yes it can be built from source. But I faced many difficulties while building solc. It required some libraries(boost-c-library), and some libraries also required some more libraries(z3). And these new libraries were also not easily available, so I had to build them(z3) too from source.

So, I am suggesting that we can use `solcjs`, which is more easily available on all platforms.

**Comment by AyushyaChitransh** [comment]
I was working to resolve this in this commit. https://github.com/AyushyaChitransh/parity-bridge/commit/c9782b3d5ed3da3a2d513e03b06274931ee0ca80

However, the files produced by `solcjs` were named differently. Currently working on renaming those files.

**Comment by tomusdrw** [comment]
It's possible to use a docker wrapper for `solc`:
```
#!/bin/bash
docker run -i --rm --user $(id -u):$(id -g) -v $(pwd)/../:/tmp --workdir /tmp/contracts ethereum/solc:stable $@
exit $?
```
