### ISSUE TITLE
error[E0432]: unresolved import `self::tokio_uds::UnixStream`

### ISSUE THREAD

**Issue by fico23** [paritytech/parity-bridge#175]
I get the following error when i execute cargo build -p parity-bridge --release in windows cmd:

Compiling web3 v0.2.0 (https://github.com/tomusdrw/rust-web3?branch=bridge#aad14c09)
     Running `rustc --crate-name web3 C:\Users\Filip\.cargo\git\checkouts\rust-web3-ebc1a09fd5a9a2a2\aad14c0\src\lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg "feature=\"default\"" --cfg "feature=\"http\"" --cfg "feature=\"hyper\"" --cfg "feature=\"ipc\"" --cfg "feature=\"tokio-core\"" --cfg "feature=\"tokio-io\"" --cfg "feature=\"tokio-uds\"" -C metadata=4c373ac4a1a6a4e2 -C extra-filename=-4c373ac4a1a6a4e2 --out-dir C:\Git\parity-bridge\target\release\deps -L dependency=C:\Git\parity-bridge\target\release\deps --extern jsonrpc_core=C:\Git\parity-bridge\target\release\deps\libjsonrpc_core-b7fe6318cc671a04.rlib --extern serde=C:\Git\parity-bridge\target\release\deps\libserde-c98a29e43db25c39.rlib --extern hyper=C:\Git\parity-bridge\target\release\deps\libhyper-5c53c645cc7342cc.rlib --extern tokio_core=C:\Git\parity-bridge\target\release\deps\libtokio_core-f4f4b38453bb6b42.rlib --extern serde_derive=C:\Git\parity-bridge\target\release\deps\serde_derive-9557dc8e929fd15d.dll --extern ethabi=C:\Git\parity-bridge\target\release\deps\libethabi-b2bc89e2b567abb2.rlib --extern serde_json=C:\Git\parity-bridge\target\release\deps\libserde_json-4f5acda50a387e97.rlib --extern arrayvec=C:\Git\parity-bridge\target\release\deps\libarrayvec-a7882ab97b3714b9.rlib --extern futures=C:\Git\parity-bridge\target\release\deps\libfutures-4934b05965fc2356.rlib --extern error_chain=C:\Git\parity-bridge\target\release\deps\liberror_chain-5d17c71ed1ffc758.rlib --extern ethereum_types=C:\Git\parity-bridge\target\release\deps\libethereum_types-5ede4b5e04d1405e.rlib --extern tokio_timer=C:\Git\parity-bridge\target\release\deps\libtokio_timer-6d45265838a1d807.rlib --extern tokio_io=C:\Git\parity-bridge\target\release\deps\libtokio_io-a86299c542ec96a6.rlib --extern rustc_hex=C:\Git\parity-bridge\target\release\deps\librustc_hex-4f875a2519e1b101.rlib --extern tokio_uds=C:\Git\parity-bridge\target\release\deps\libtokio_uds-054453e0ca483236.rlib --extern log=C:\Git\parity-bridge\target\release\deps\liblog-72b3020438a4dc38.rlib --extern parking_lot=C:\Git\parity-bridge\target\release\deps\libparking_lot-f7d4f1f53d1a324a.rlib --cap-lints allow`
**error[E0432]: unresolved import `self::tokio_uds::UnixStream`
  --> C:\Users\Filip\.cargo\git\checkouts\rust-web3-ebc1a09fd5a9a2a2\aad14c0\src\transports\ipc.rs:10:5
   |
10 | use self::tokio_uds::UnixStream;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `UnixStream` in the root**

**Comment by snd** [comment]
the error originates from tokio_udx (unix domain sockets) which is used by web3 which is used by the bridge.

the bridge currently uses unix domain sockets to communicate over jsonrpc with ethereum nodes.

as such **the bridge currently does not support windows as there are no unix domain sockets on windows.**

once the https://github.com/paritytech/parity-bridge/tree/snd-refactor branch is completed and merged the bridge will use HTTP instead of unix domain sockets. then it could possibly work on windows. though there might be other issues with windows

**Comment by fico23** [comment]
thanks for the info
