### ISSUE TITLE
Compatibility with geth

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/parity-bridge#177]
I am not sure how it can be made possible. But there were problems in connecting parity-bridge using geth.

When I looked further, I found the web3 version being used in this project is few months behind the present version of rust-web3. New commits in the rust-web3 indicate web3 is now compatible to retrieve filters from geth.

The compatibility of parity-bridge to work with geth can be achieved by updating the rust-web3 library.

**Comment by snd** [comment]
@JosefJ nice! it's pretty much done. just requires a code review
