### ISSUE TITLE
Bridge.db not found

### ISSUE THREAD

**Issue by vanruch** [paritytech/parity-bridge#179]
After trying to run, the following error is printed
```
ivan[17:29:22]:~/parity-bridge$env RUST_LOG=info parity-bridge --config bridge_config.toml --database bridge.db
INFO:parity_bridge: Parsing cli arguments
INFO:parity_bridge: Loading config
INFO:parity_bridge: Starting event loop
INFO:parity_bridge: Establishing ipc connection
File "bridge.db" not found
```
According to readme the new database should be created [--database - location of the database file. if there is no file at specified location, new bridge contracts will be deployed and new database will be created](https://github.com/paritytech/parity-bridge#run)

**Comment by snd** [comment]
strange indeed. i found the whole database handling a bit complicated and refactored it amongst other things. it's not merged yet. will revisit this then

**Comment by nicolashardy** [comment]
Try with parity-bridge-deploy instead of parity-bridge

**Comment by nicolashardy** [comment]
@ArvsIndrarys try running `cargo build -p parity-bridge-deploy --release` and then the parity-bridge-deploy binary should exist

**Comment by ArvsIndrarys** [comment]
That worked for me ! I had to checkout the master branch back though.
