### ISSUE TITLE
Error when compiling the bridge for linux

### ISSUE THREAD

**Issue by makue1105** [paritytech/parity-bridge#181]
We're trying to compile the bridge on a linux environment and it keeps failing.

* 1st error: the github branch for rust-web3 does not exist anymore or is not accessible 
(web3 = { git = "https://github.com/tomusdrw/rust-web3", branch = "bridge" }) so the compilation aborted at this point. We tried to fix this error by switching the branch in the cargo.toml file to "master" and the compilation continued. 

* 2nd error:  we're receiving the following error: 
```
note: Perhaps two different versions of crate `ethereum_types` are being used?
  --> bridge/src/message_to_mainnet.rs:47:39
   |
47 |             sidenet_transaction_hash: hash,
   |                                       ^^^^
error[E0308]: mismatched types
  --> bridge/src/message_to_mainnet.rs:48:32
   |
48 |             mainnet_gas_price: withdraw_log.home_gas_price,
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ethereum_types::U256`, found struct `web3::types::U256`
   |
   = note: expected type `ethereum_types::U256`
              found type `web3::types::U256`
note: Perhaps two different versions of crate `ethereum_types` are being used?
  --> bridge/src/message_to_mainnet.rs:48:32
   |
48 |             mainnet_gas_price: withdraw_log.home_gas_price,
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to 9 previous errors
Some errors occurred: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `bridge`.
To learn more, run the command again with --verbose.
```

For compiling we used rustc 1.27.1 (5f2b325f6 2018-07-07)

**Comment by bjornwgnr** [comment]
I reckon it makes sense to hold off until the major refactoring PR https://github.com/paritytech/parity-bridge/pull/159 is merged but @snd should be able to tell more.

**Comment by tomusdrw** [comment]
@makue1105 The branch has been restored. The compilation should work now.
