### ISSUE TITLE
'ethereum-based blockchain'

### ISSUE THREAD

**Issue by luca590** [paritytech/parity-bridge#185]
This term is referring to chains that use the EVM (or something very similar) like testnets and ETC?

**Comment by snd** [comment]
the testnets (kovan, ropsten, rinkeby), ETC and ETH should all work with the bridge in principle. they all support deploying/executing EVM bytecode (bridge requires deployment of EVM bytecode) and can be connected to with the ethereum clients (parity, geth, ...) which support the ethereum jsonrpc (bridge connects to a node via jsonrpc)
