### ISSUE TITLE
build failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by pillsgrim** [paritytech/parity-bridge#187]
Hello, 
I am trying to build parity-bridge on linux but i encounter the following error:

```
error: failed to run custom build command for `bridge v0.4.0 (file:///home/dcipher/parity-bridge/bridge)`
process didn't exit successfully: `/home/dcipher/parity-bridge/target/release/build/bridge-fb87de0acaeac7a8/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../contracts/bridge.sol
cargo:rustc-env=GIT_HASH=53c56a2440493323ea2a5ad122036e226d7aa610


--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

```
I followed the guide you provided under **build** section of README.md.
What am I missing? 
Any workaround?
Thank you

**Comment by JosefJ** [comment]
which rust version are you running?
`rustc -V`

**Comment by pillsgrim** [comment]
Hello Josef, it looks like rust got updated to version 1.28. 
I tried to build the project with rust version 1.27 and 1.28, failed with the same error(as you can see above) for both versions.
Thanks
```
$ rustc -V
```
```
rustc 1.28.0 (9634041f0 2018-07-30)
```

**Comment by pillsgrim** [comment]
Horay, it seems i was missing those two libraries, `pkg-confi`, `libssl-dev `.Somehow missed them on the log. All good now, it builds as it should.
Thanks!!!
