### ISSUE TITLE
Impossible to deploy the bridge

### ISSUE THREAD

**Issue by nicolashardy** [paritytech/parity-bridge#192]
Hello

I cannot deploy the parity-bridge

When using `env RUST_LOG=info parity-bridge-deploy --config bridge_config.toml --database db.toml`

Here is the output

```
INFO:parity_bridge_deploy: Parsing cli arguments
INFO:parity_bridge_deploy: Loading config
INFO:parity_bridge_deploy: Starting event loop
INFO:parity_bridge_deploy: Establishing HTTP connection to main "http://localhost:8549"
INFO:parity_bridge_deploy: Establishing HTTP connection to side "http://localhost:8540"
INFO:parity_bridge_deploy: Deploying MainBridge contract
INFO:bridge::deploy: sending MainBridge contract deployment transaction and waiting for 0 confirmations...
INFO:bridge::deploy: MainBridge deployment completed to 0x9a6ff80c82bbd7e60bd1ded1fd93f7bd40a1eeab
INFO:parity_bridge_deploy: Successfully deployed MainBridge contract
INFO:bridge::deploy: "deployment-main-9a6ff80c82bbd7e60bd1ded1fd93f7bd40a1eeab" created
INFO:parity_bridge_deploy: Deploying SideBridge contract
INFO:bridge::deploy: sending SideBridge contract deployment transaction and waiting for 0 confirmations...
DeploySide: deployment transaction failed

Caused by:
	RPC error: Error { code: ServerError(-32020), message: "Your account is locked. Unlock the account via CLI, personal_unlockAccount or use Trusted Signer.", data: Some(String("SStore(InvalidAccount)")) }
```

It was working pretty good with the previous version (1 month ago)

Do you have any idea ?

For information my Authority is unlocked with 

``` 
[account]
unlock= [
   "0x000....."
]
password=["node.pwds"]
```

**Comment by ArvsIndrarys** [comment]
Apparently, there was no problem on the Main network. Is there a difference between the definition of your Main and Side network?

I deployed parity bridge between two private networks and ![here](https://gist.github.com/ArvsIndrarys/cdbc2e5cfb3e4503d976ad98a6c7541e) is the link of the definition of one of my node.

**Comment by nicolashardy** [comment]
Thank you for your answer

My main network is a Ropsten-like (but local) network
My side network is a PoA network

I've seen your file and it seems pretty much like mine

**Comment by ArvsIndrarys** [comment]
Does the node have enough ETH to pay for the deployment?

**Comment by branciard** [comment]
Hi,  
At the first launch the db.toml is empty right ? 
I was expected as said in the readme :  _if there is no file at specified location, new bridge contracts will be deployed and new database will be created_
but I have : 
``` 
parity-bridge/target$ ./release/parity-bridge --config ../bridge_config.toml --database db.toml
File "db.toml" not found
``` 
And if I create a db.toml empty file, I have to set contracts addresses values.
I missed something ?

**Comment by debris** [comment]
@branciard use ./release/parity-bridge-**deploy** to deploy the bridge

**Comment by branciard** [comment]
Ok I see. thanks @debris
