### ISSUE TITLE
send_transaction_with_confirmation fails at parity-bridge-deploy

### ISSUE THREAD

**Issue by branciard** [paritytech/parity-bridge#196]
## Environment : 
- OS ubuntu with [this bootstrap](https://github.com/branciard/blockchain-dev-env/blob/master/bootstrap-ubuntu-aws.sh) 
- Parity docker image version: parity/parity:stable
- Parity config POA using [parity-deploy](https://github.com/paritytech/parity-deploy) : 
```
./parity-deploy.sh --config aura --name ${CHAIN_NAME} --nodes ${CHAIN_NODES} --ethstats --expose
```
## Error : 

```
env RUST_LOG=debug ./release/parity-bridge-deploy --config ../iexec-bridge-test.toml --database ./db.toml
```
Deploy contract transaction in mined successfully in ethereum-parity client logs : 
```
host1        | 2018-09-25 13:28:48 UTC Transaction mined (hash 0xe2ba7441691034a279bba39b9179b5dd78560c17b43d86e504a33f58daf6b52d)
```
But the client fails with the following error : 
```
thread 'main' panicked at 'receipt can't be null after wait for confirmations; qed', libcore/option.rs:989:5
```

## Solution : 

I forked the [rust-web3](https://github.com/tomusdrw/rust-web3)  and add a tempo (basically wait transaction to be mined and receipt ready) in the branch here [add-tempo](https://github.com/branciard/rust-web3/commit/fd8638e2b30a285a5d39dd50836da6d63237dc26) to dirty quick test. 
I change the dependancy in Cargo.toml : 
```
web3 = { git = "https://github.com/branciard/rust-web3", branch = "add-tempo"  }
```
With this quick dirty fix, parity-bridge-deploy passed for home and foreign bridge contracts creation.

Do you think it is more an issue in rust-web3 client lib ? 
and I should open in rust-web3 github repo ?

**Comment by debris** [comment]
it is a bug in the bridge itself. I believe it is caused by the same wrong assumption that https://github.com/paritytech/parity-bridge/issues/191#issuecomment-420287324

> error occurs, because receipt is returned for a transaction which is a part of pending block (not yet mined)

**Comment by branciard** [comment]
ok thank you @debris. 

I can see also a wrong transaction receipt interpretation in web3js as well when interacting with the contract. So this is not linked to the client web3rust. Maybe neither cause by a parity-bridge bug ?. But maybe to how the transaction receipt is formatted or create in my PoA network ? Maybe due to 'confirmationNumber' 0 ?

When I try to deposit some eth on the MainBridge Contract, the web3js client interpret the transaction as 'Error: Transaction has been reverted by the EVM'  but in reality it was not : state is updated and we can see event log in the receipt.

Here the code of the deposit.js :

```
const Web3 = require('web3');//version"web3": "^1.0.0-beta.36"
var MSG_SENDER = process.argv[2] || "0x0513425AE000f5bAEaD0ed485ED8c36E737e3586";
var SMART_CONTRACT_ADDRESS = process.argv[3] || "0x8eb1ca3fe740a2b4b5424de7a5334127b6d8c0ba";
var NODE_TARGET = process.argv[4] || "http://IP_HERE:8545";

web3 = new Web3(new Web3.providers.HttpProvider(NODE_TARGET));


try {
  web3.eth.sendTransaction({
      from: MSG_SENDER,
      to: SMART_CONTRACT_ADDRESS,
      value: "10"
    })
    .on('transactionHash', function(hash) {
      console.debug("depositTx : " + hash);
    })
    .on('receipt', function(receipt) {
      console.debug("receipt : " + receipt);
    })
    .on('confirmation', function(confirmationNumber, receipt) {
      console.debug("confirmationNumber : " + confirmationNumber);
    })
    .on('error', function(error) {
      console.error("sendTransaction error !");
      console.error(error);
      process.exit(1);
    }); 
} catch (err) {
  console.error(err);
  process.exit(1);
}
```

 The result 

```
node deposit.js
depositTx : 0xbe702baebcae5135c52fcff1d7b070d20a3ba94d7ce61dd2078d28d43606f4f0
confirmationNumber : 0
sendTransaction error !
Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x4727031e1445f61036f81b5a0e0b9e3807fb2f7adf4128cdd9ccda9a7c842194",
  "blockNumber": 5060,
  "contractAddress": null,
  "cumulativeGasUsed": 23834,
  "from": "0x0513425ae000f5baead0ed485ed8c36e737e3586",
  "gasUsed": 23834,
  "logs": [
    {
      "address": "0x8EB1cA3fE740A2b4B5424De7a5334127B6D8C0ba",
      "blockHash": "0x4727031e1445f61036f81b5a0e0b9e3807fb2f7adf4128cdd9ccda9a7c842194",
      "blockNumber": 5060,
      "data": "0x0000000000000000000000000513425ae000f5baead0ed485ed8c36e737e3586000000000000000000000000000000000000000000000000000000000000000a",
      "logIndex": 0,
      "removed": false,
      "topics": [
        "0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c"
      ],
      "transactionHash": "0xbe702baebcae5135c52fcff1d7b070d20a3ba94d7ce61dd2078d28d43606f4f0",
      "transactionIndex": 0,
      "transactionLogIndex": "0x0",
      "type": "mined",
      "id": "log_8d77dcab"
    }
  ],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000020000100000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000400000000000000000",
  "root": null,
  "status": false,
  "to": "0x8eb1ca3fe740a2b4b5424de7a5334127b6d8c0ba",
  "transactionHash": "0xbe702baebcae5135c52fcff1d7b070d20a3ba94d7ce61dd2078d28d43606f4f0",
  "transactionIndex": 0
}
    at /Users/fbranci/iexecdev/parity-bridge/tools/node_modules/web3-core-method/src/index.js:364:46
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I have not try but I suppose that it works with PoA Kovan network. So, I will try to set the same params config (eip support etc ...) as seen here : 
https://github.com/paritytech/parity-ethereum/blob/master/ethcore/res/ethereum/kovan.json#L42
I will update if it correct the problem.
