### ISSUE TITLE
after installing solc having the error solc --version failed to run

### ISSUE THREAD

**Issue by RushabhParmar12** [paritytech/parity-bridge#209]
error: failed to run custom build command for `bridge-contracts v0.5.0 (C:\Users\lenovo\Desktop\parity-bridge-master\contracts)`
process didn't exit successfully: `C:\Users\lenovo\Desktop\parity-bridge-master\target\release\build\bridge-contracts-8211701ae21cc47d\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../contracts/bridge.sol
cargo:rustc-env=GIT_HASH=

--- stderr
thread 'main' panicked at '`solc --version` failed to run. run it yourself to verify. file an issue if this persists: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', libcore\result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `bridge v0.5.0 (C:\Users\lenovo\Desktop\parity-bridge-master\bridge)`
process didn't exit successfully: `C:\Users\lenovo\Desktop\parity-bridge-master\target\release\build\bridge-45ef11f6e31bad24\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../contracts/bridge.sol
cargo:rustc-env=GIT_HASH=

--- stderr
thread 'main' panicked at '`solc --version` failed to run. run it yourself to verify. file an issue if this persists: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', libcore\result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by joshua-mir** [comment]
can you please share the output of attempting to run `solc` on your own? make sure you haven't installed solcjs, for example

**Comment by tomusdrw** [comment]
The error should be improved with https://github.com/paritytech/rust_solc/pull/8 please re-open if the issue persists.
