### ISSUE TITLE
CollectedSignatures authority should be an indexed topic

### ISSUE THREAD

**Issue by debris** [paritytech/parity-bridge#30]

**Comment by snd** [comment]
@debris can you elaborate?

**Comment by debris** [comment]
`address authority` should be changed to `address indexed authority`. And the rust code should be changed accordingly

https://github.com/paritytech/parity-bridge/blob/6cec01f8f0e669b08e16362c4c234a4ac7347cb9/contracts/bridge.sol#L201-L202

**Comment by debris** [comment]
this allows us to easily track who is responsible for the relay
