### ISSUE TITLE
check, write tests and audit for solidity functions

### ISSUE THREAD

**Issue by debris** [paritytech/parity-bridge#4]

**Comment by akolotov** [comment]
@debris, have found a minor issue in the function `transfer()` of `ForeignBridge`. The balance increased without the check if the balance could overflow.

**Comment by debris** [comment]
is it enough if I add these two assertions?

```solidity
require(value != 0);
require(balances[msg.recipient] + value > balances[msg.recipient]);
```

**Comment by akolotov** [comment]
Right. I should be OK.

**Comment by snd** [comment]
@debris i think this has been superseded by other issues. can we close this and add an "audit for contract code" issue?

**Comment by debris** [comment]
sure!
