### ISSUE TITLE
Describe required parity version in the docs

### ISSUE THREAD

**Issue by debris** [paritytech/parity-bridge#42]

**Comment by snd** [comment]
@debris what's the required parity version? integration test (https://github.com/paritytech/parity-bridge/pull/95/files) passes with `1.8.6`

**Comment by debris** [comment]
I don't know, so let's make 1.8.6 a required version :)

**Comment by snd** [comment]
described now in deployment guide introduced in https://github.com/paritytech/parity-bridge/pull/123
