### ISSUE TITLE
have solc versions for test and deploy match up

### ISSUE THREAD

**Issue by debris** [paritytech/parity-bridge#43]

**Comment by snd** [comment]
`solc` is working fine. do we still need this and why?

**Comment by snd** [comment]
the dependency on solc is lighter than the dependency on truffle. closing this for now. feel free to reopen

**Comment by debris** [comment]
> `solc` is working fine. do we still need this and why?

truffle tests code compiled with truffle (old version of compiler), whereas we deploy code compiled with a newer version of compiler

> the dependency on solc is lighter than the dependency on truffle. closing this for now. feel free to reopen

that's a shame.

let's keep it closed for now and revisit in future when it's feasible

**Comment by snd** [comment]
> truffle tests code compiled with truffle (old version of compiler), whereas we deploy code compiled with a newer version of compiler

now i understand the issue. the heading just specified the "what", not the "why".
it would be nice to have the test/deploy versions match up

**Comment by debris** [comment]
replaced by #169
