### ISSUE TITLE
Purpose of truncate function

### ISSUE THREAD

**Issue by igorbarinov** [paritytech/parity-bridge#51]
```
    function truncate (address[] storage self, uint len) internal {
        for (uint i = len; i < self.length; i++) {
            delete self[i];
        }
        self.length = len;
    }
```
it's not used.
Question is what is the purpose of this function?

**Comment by debris** [comment]
just legacy code, it should be removed

**Comment by igorbarinov** [comment]
@vbaranov please remove in our contract and send a PR here
@rstormsf here is an answer to your question you raised about truncate. Thanks!
