### ISSUE TITLE
consider splitting ForeignBridge.transfer into two functions

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#55]
currently `ForeignBridge.transfer` takes a boolean as last argument that switches between two very different behaviours. `false` simply changes balances whereas `true` kicks off an entire relay.

https://github.com/paritytech/parity-bridge/blob/0149ef8cefc3a7d111c54b6b996f30376912a956/contracts/bridge.sol#L210

imho this is confusing and easy to get wrong with potentially bad consequences.

i think it would be good to split this into two functions.
`transferOnChain(recipient, value)` and `transferToHomeChain(recipient, value)` for example.

**Comment by snd** [comment]
@debris what are your thoughts on this?

**Comment by debris** [comment]
I agree!
