### ISSUE TITLE
in HomeBridge.withdraw: recipient gets loaded from message with wrong offset and contains wrong data

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#61]
code in question: https://github.com/paritytech/parity-bridge/blob/740601530096c261695ba9216b5e9d5f871a229f/contracts/bridge.sol#L119

look here for how message is constructed:
https://github.com/paritytech/parity-bridge/blob/59403966fc774bc3c0dc943b27d62f2c3ff8939a/bridge/src/bridge/withdraw_confirm.rs#L29

message format:
- 20 bytes recipient
- 32 bytes value
- 32 bytes transactionHash

the code currently mistakenly thinks the format is:
- **32** bytes recipient
- 32 bytes value
- 32 bytes transactionHash

all three values read in `HomeBridge.withdraw` are corrupted because of this.

found while writing tests for HomeBridge.withdraw (https://github.com/paritytech/parity-bridge/issues/60).

i've got a fix on the `issue-54-close-attack-vector` branch:
https://github.com/paritytech/parity-bridge/pull/56/commits/fed0cc1aaa4e4067fa3bde26aaa4c081cdc8897b

**Comment by snd** [comment]
@debris can you have a look at this when you have a free moment. thanks

**Comment by tomusdrw** [comment]
`bytes message` is always:
32 bytes - length of the content
20 bytes - address
32 bytes - uint
32 bytes - hash
`mload(add(message, 0x20))` just skips the length (since we know it anyway)
The error is in:
`value := mload(add(message, 0x40))` actually, cause we skip len (32b) and address (32b instead of 20b) unless we expect address to be padded to 32bytes (which seems to be missing in docs).

**Comment by snd** [comment]
address is currently not padded to 32bytes. see https://github.com/paritytech/parity-bridge/blob/59403966fc774bc3c0dc943b27d62f2c3ff8939a/bridge/src/bridge/withdraw_confirm.rs#L29

**Comment by snd** [comment]
@tomusdrw thanks for taking a look at this!

i didn't know that the first 32bytes  of a `bytes` represent the length. makes total sense.

what confuses me is that this test https://github.com/paritytech/parity-bridge/blob/b796746a5d1a3baa812b9ab832500c67ab176c7e/truffle/test/home.js#L85
only works if i modify the assembly to this: https://github.com/paritytech/parity-bridge/blob/b796746a5d1a3baa812b9ab832500c67ab176c7e/contracts/bridge.sol#L119

if i modify the assembly to:
```
        assembly {
            // skip 32 bytes message length
            recipient := mload(add(message, 32))
            value := mload(add(message, 52))
            hash := mload(add(message, 84))
        }
```
which i'd expect to be correct

then what gets loaded into `recipient` is wrong and the test fails at:
https://github.com/paritytech/parity-bridge/blob/b796746a5d1a3baa812b9ab832500c67ab176c7e/truffle/test/home.js#L129

**Comment by snd** [comment]
i think we need to pad address to 32 bytes since `mload` seems to always load 32 bytes

**Comment by snd** [comment]
https://github.com/paritytech/parity-bridge/issues/61#issuecomment-350236434

what happens here is probably that bytes 20-32 are all 0 since length is `84`.
thus reading recipient from bytes 20-52 (32 bytes starting at 20) reads 12 zero bytes followed by the 20 recipient bytes which get correctly read as the recipient address.
we could leave it like this since length is always `84` but it would probably be cleaner to pad recipient to 32

**Comment by snd** [comment]
> That should work, right? We re-use some bytes from length, but it doesn't matter cause they are discarded anyway.

yes, that works!

> Otherwise we need to pad address to 32-bytes.

that would be a bit clearer imho

**Comment by snd** [comment]
how should we resolve this?

1) re-use some bytes from length and document it thoroughly
2) pad address to 32-bytes

fine with both. i like 2 a bit more

**Comment by tomusdrw** [comment]
I prefer the first one to reduce the gas cost by a tiny bit. That said we should heavily test that function to make sure it's correct. I would also add length assertion at the top if it's not there yet, so that a padded address is not accepted.

**Comment by snd** [comment]
> I prefer the first one to reduce the gas cost by a tiny bit. That said we should heavily test that function to make sure it's correct. I would also add length assertion at the top if it's not there yet, so that a padded address is not accepted.

ok!

already added a length assertion
