### ISSUE TITLE
single malicious authority can block withdraw

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#64]
currently for each withdraw one authority (the one submitting the last required signature) is selected to do the relay (call `HomeBridge.withdraw`).

if this authority is malicious and doesn't call `HomeBridge.withdraw` then the ether is never paid out on `home_chain`.

we should remove this single point of failure

update:
withdraws are not "stuck forever". anyone can execute a transaction to make them complete. it's just that this doesn't happen automatically. also read: https://github.com/paritytech/parity-bridge/issues/64#issuecomment-351665498

**Comment by snd** [comment]
what about not selecting a single authority but having all authorities call `HomeBridge.withdraw` if they see a `CollectedSignatures` on `foreign_chain`?

all but the first such call will be reverted because of:
https://github.com/paritytech/parity-bridge/blob/740601530096c261695ba9216b5e9d5f871a229f/contracts/bridge.sol#L125

now only one honest authority is required for this step.

are there any downsides to this approach?

**Comment by rphmeier** [comment]
(as discussed in person, all those authorities pay the fee. we considered having authorities take turns of X blocks of being in charge of all pending withdraws.)

**Comment by snd** [comment]
related #16

**Comment by snd** [comment]
this is less of an issue than i thought:

if the authority chosen to do the relay fails to do so, then any other user (not just authorities) is free to call `HomeBridge.withdraw`. if enough signatures were collected (`ForeignBridge.CollectedSignatures` exists for message) then any user can collect the signatures from `foreign_chain` and do the call.

so the issue is not that withdraw relays will never happen if the chosen authority is bad but rather that they will not happen automatically.

such unfinished withdraws should be detected and retried automatically

**Comment by snd** [comment]
as @rphmeier suggested we could have authorities take turns (a la aura) in being responsible for relaying withdraws. the current primary authority would then be responsible for calling `HomeBridge.withdraw` for all `ForeignBridge.CollectedSignatures` events that are *finalized* on the `foreign_chain` but for which no proof of the call to `HomeBridge.withdraw` is currently present in the longest `home_chain`, until such proof is *finalized* (n-blocks deep) on `home_chain`.
that should resolve the issue
