### ISSUE TITLE
compiled contracts in version control

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#78]
currently some compiled contracts `.bin` and `.abi` are checked into git.

these have the tendency to get stale. it's cumbersome and easy to forget to keep them up to date.

why are they checked in?
should we remove them from version control? 

afaik https://github.com/paritytech/contracts doesn't have them checked in either

**Comment by snd** [comment]
compiled ABIs are required for the bridge rust code: https://github.com/paritytech/parity-bridge/blob/7e6d443fba1975f621af83a5af7bd666c38c59c4/bridge/src/contracts.rs#L1

we could remove them from version control and compile them in a `build.rs`

**Comment by debris** [comment]
yes, we can do that. The only downside is that it brings additional dependency to a build system. Either solc or it's js version

**Comment by snd** [comment]
resolved in https://github.com/paritytech/parity-bridge/pull/94
