### ISSUE TITLE
refactor library contracts

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#82]
a couple of proposals that could make the library contracts a bit more self explaining:

- rename `Signer` to `MessageSigning`
- rename function `Signer.signer` to `recoverAddressFromSignedMessage`
- rename function `Signer.hash`to `hashMessage`
- maybe we can make `recoverAddressFromSignedMessage` and `hashMessage` `public`. they are `pure` meaning they don't read/write any state and should be safe to make `public`. then we can get rid of `SignerTest` which is only a public wrapper around `Signer.signer` 
- move `Authorities.contains` to `Utils`, rename it to `addressArrayContains` and use it like `Utils.addressArrayContains(authorities, msg.sender)` for example. i find the `using Authorities for address[];` a bit strange.
- move `getXFromMessage` for `X = {Value, Recipient, TransactionHash}` into a `Message` library so documentation and code related to messages is found in one place and doesn't clutter `HomeBridge`

@debris what do you think?

**Comment by debris** [comment]
> - maybe we can make `recoverAddressFromSignedMessage` and `hashMessage` `public`. they are `pure` meaning they don't read/write any state and should be safe to make `public`. then we can get rid of `SignerTest` which is only a public wrapper around `Signer.signer` 

It may alter the way solc generates contracts. Right now, both `HomeBridge` and `ForeignBridge` are standalone and the bytecode of `Signer` is inlined and stored together with them. If you make `Signer` functions public, solc may compile it as a contract and each call to it's functions will be an external call (which is more expensive). Also the way contracts are initialised will change. I'm not saying we shouldn't do it, but it may be more difficult than it seems to be

I like all other changes ;)

**Comment by snd** [comment]
i wasn't aware that `solc` handles library functions this way. makes sense though.

**Comment by snd** [comment]
resolved in https://github.com/paritytech/parity-bridge/pull/83
