### ISSUE TITLE
Duplication of value extraction from the message

### ISSUE THREAD

**Issue by akolotov** [paritytech/parity-bridge#89]
https://github.com/paritytech/parity-bridge/blob/1cef1596a48edbf360833e23420e4d76020d8f75/contracts/bridge.sol#L243

The code is written as so the value extracted from the message in L231 and after that it is extracted again as part of the check if relay expenses could be covered. It unnecessarily increases costs which should be covered by end users.

**Comment by snd** [comment]
closing this as it no longer applies after merging https://github.com/paritytech/parity-bridge/pull/114
