### ISSUE TITLE
Extend example with other transaction parameters

### ISSUE THREAD

**Issue by akolotov** [paritytech/parity-bridge#91]
https://github.com/paritytech/parity-bridge/blob/1cef1596a48edbf360833e23420e4d76020d8f75/examples/config.toml#L25-L28

Currently example of configuration in README.md and the example of configuration file in the source tree does not reflect such parameters as `withdraw_confirm` and `withdraw_relay`. This causes the situation when the bridge transactions are not valid since 0 gas is set when transactions are composed. This leads to bridge termination and the reason is not evident.

It makes sense to update gas usage for `deposit_relay` transactions since the transactions fails silently without any report or log in the console due to the current configuration in the example `gas = 100000`.

**Comment by snd** [comment]
@akolotov good find. are you interested in doing a PR?

**Comment by akolotov** [comment]
Here is my measurements for one authority in the list:

```
home_deploy = 910580
foreign_deploy = 1652029
deposit_relay = 90861
withdraw_confirm = 265380
withdraw_relay = ???
```

Cannot get value for `withdraw_relay` due to the issue https://github.com/paritytech/parity-bridge/issues/87

**Comment by akolotov** [comment]
#87 fixed. So I can measure the last operation:

```
withdraw_relay = 72444
```

**Comment by snd** [comment]
resolved in https://github.com/paritytech/parity-bridge/pull/121
