### ISSUE TITLE
bridge ERC20 tokens (deposit ERC20 on home, get ERC20 on foreign)

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#93]
unrelated to #85

use cases:
- exchange on a federated side-chain

tricky because https://github.com/paritytech/parity-bridge#recipient-pays-relay-cost-to-relaying-authority doesn't work with entirely "virtual" tokens that can't be used to pay for gas costs.
would reopen attack vector https://github.com/paritytech/parity-bridge/issues/54

**Comment by bjornwgnr** [comment]
https://github.com/gnosis/gnosis-exchange could potentially work as on-chain price oracle for ERC20 tokens

cc https://github.com/Georgi87

**Comment by sponnet** [comment]
Some time ago we've built an experimental service to exchange any traded ERC-20 token for an amount of gas. The problem to solve was to have an account with 0 ETH but an ERC-20 token balance be able to send their tokens. https://github.com/swarmcity/SCLabs-gasstation-service This might make it possible to pay in the mainnet ERC-20 token for the gas.

**Comment by snd** [comment]
for this repo we'll concentrate on an arbitrary message passing bridge that this can be built on top of
