### ISSUE TITLE
tooling to observe health/usage of a running bridge system

### ISSUE THREAD

**Issue by snd** [paritytech/parity-bridge#97]
**so we have an easy way to see whether and how people are using the bridge and what's going wrong**

useful for status pages, troubleshooting, usage statistics, etc

## steps

1. script that computes one stat (which?)
2. add stats
3. HTTP server API that a web frontend could use.

## inputs

- database file
- ...

## implementation

connects to both chains. gets logs (https://paritytech.github.io/wiki/JSONRPC-eth-module.html#eth_getlogs). iterates through logs and collects stats

## ideas for stats to compute

- gas costs saved
  - by transacting on ForeignBridge
- total ether bridged
- total number of users (addresses)
- number of deposits that have not been relayed
  - `> 0` = fault
- number of withdrawals that have not been relayed
  - `> 0` = fault
- x value deposited in y transactions into HomeBridge
- y value withdrawn in y transactions
- actual gas costs
  - per function
  - min, max, median
- total amount of ether in HomeBridge
- addresses in authority set that have not done any relays (deposit, submitSignature, withdraw) in {timerange}
  - sign that authority is faulty or malicious
- average relay time
- totalSupply on ForeignBridge
  - possibly over time
- withdrawals ignored because they can't cover gas cost
- withdrawals that don't have enough signatures
- gas costs
- etc

**Comment by tomusdrw** [comment]
Might be good to plug into https://github.com/poanetwork/bridge-monitor
